{% set name = "pygridmet" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygridmet-{{ version }}.tar.gz
  sha256: 048d83177824fe60e79aa30142b03a3dbb0d2df1a0dbc766575fff7a65d369d2

build:
  entry_points:
    - pygridmet = pygridmet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=60
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - async-retriever <0.17,>=0.16
    - click >=0.7
    - geopandas >=0.10
    - numpy >=1.21
    - pandas >=1
    - pygeoogc <0.17,>=0.16
    - pygeoutils <0.17,>=0.16
    - pyproj >=3.0.1
    - shapely >=2
    - xarray >=2023.01

test:
  imports:
    - pygridmet
  commands:
    - pip check
    - pygridmet --help
  requires:
    - pip

about:
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  home: https://github.com/hyriver/pygridmet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
